/**
 * Vendor the GridAtlas Teleprinter drivers into one GridAtlas cartridge part.
 * ---------------------------------------------------------------------------
 * GridAtlas ships an immutable shell plus hashed cartridges, and a cartridge is
 * ONE classic script assembled from a list of parts. That is not a limitation
 * to be worked around; it is the thing that makes a served generation
 * reproducible. So the drivers, which are authored as ES modules here, are
 * mechanically transformed into one part rather than imported at runtime.
 *
 * WHY NOT A RUNTIME import(). The atlas is served at /gridatlas/atlas/ AND at
 * /gridatlas/atlas/v/<generation>/, and a pinned generation is byte-identical
 * to the live one. A relative specifier therefore resolves to a different place
 * depending on which URL the reader opened, and an absolute one pins a pinned
 * build to whatever the live engine happens to be tomorrow -- which is exactly
 * the "improvements went backwards into a published version" failure this
 * estate has already had once. Concatenation has neither problem.
 *
 * WHY A SCRIPT AND NOT A COPY-PASTE. A hand-copied part drifts from its source
 * silently. This records the SHA-256 of every source file in the generated
 * header, so `verify` can prove the part still matches the drivers it claims to
 * be built from, and a drifted part is a failed check rather than a surprise.
 *
 *   node drivers/gridatlas/build-part.mjs <gridatlas-repo> [--verify]
 */
import { readFile, writeFile, readdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SOURCES = ['screen-frame.js', 'print-pdf.js', 'print-source-code.js'];

const target = process.argv[2];
const verifyOnly = process.argv.includes('--verify');
if (!target) {
  console.error('usage: node build-part.mjs <gridatlas-repo> [--verify]');
  process.exit(2);
}

/* The transform is deliberately dumb and total: every `export ` prefix is
   dropped and every intra-driver import line is removed, because the three
   files become one scope. Anything cleverer -- a real module graph, a bundler
   -- would be a second thing to trust. If a driver ever imports something that
   is NOT one of its siblings, this refuses rather than emitting a part with a
   dangling reference. */
function flatten(name, text) {
  const lines = text.split(/\r?\n/);
  const out = [];
  for (const line of lines) {
    const importMatch = line.match(/^\s*import\s+.*from\s+'\.\/([^']+)';?\s*$/);
    if (importMatch) {
      if (!SOURCES.includes(importMatch[1])) {
        throw new Error(`${name} imports ${importMatch[1]}, which is not vendored`);
      }
      continue;
    }
    if (/^\s*import\s/.test(line)) {
      throw new Error(`${name} has an import this build cannot flatten: ${line.trim()}`);
    }
    out.push(line.replace(/^(\s*)export\s+(async\s+function|function|const|let|class)\s/, '$1$2 '));
  }
  return out.join('\n');
}

const hashes = {};
const bodies = [];
for (const name of SOURCES) {
  const text = await readFile(path.join(HERE, name), 'utf8');
  hashes[name] = createHash('sha256').update(text).digest('hex');
  bodies.push(`  /* ---- ${name} (sha256 ${hashes[name].slice(0, 16)}) ---- */\n`
    + flatten(name, text).split('\n').map(l => (l ? '  ' + l : l)).join('\n'));
}

const wiring = await readFile(path.join(HERE, 'gridatlas-wiring.js'), 'utf8');
hashes['gridatlas-wiring.js'] = createHash('sha256')
  .update(wiring).digest('hex');

const header = `/**
 * TELEPRINT CONTROLS -- GENERATED. DO NOT EDIT THIS FILE.
 *
 * Built by teleprinter/drivers/gridatlas/build-part.mjs from the drivers in
 * that directory, which are where any change belongs. Editing this copy makes
 * the served bytes disagree with the source they claim to come from, and
 * --verify will say so.
 *
 * Two SEPARATE functions, on the architect's instruction:
 *   Print PDF          a picture of the reader's screen, for a person
 *   Print source code  the entire source and its dependencies, for a machine
 *
 * Sources:
${Object.entries(hashes).map(([k, v]) => ` *   ${k}  sha256 ${v}`).join('\n')}
 */
`;

const part = header + '(function () {\n  \'use strict\';\n\n'
  + bodies.join('\n\n') + '\n\n'
  + wiring.split('\n').map(l => (l ? '  ' + l : l)).join('\n')
  + '\n}());\n';

const partPath = path.join(target, 'atlas', 'modules', 'teleprint-controls.js');
const existingDir = await readdir(path.join(target, 'atlas', 'modules'));
const existing = existingDir.filter(name => /teleprint-controls\.js$/.test(name));

if (verifyOnly) {
  if (!existing.length) {
    console.error('no vendored teleprint-controls part found');
    process.exit(1);
  }
  let bad = 0;
  for (const name of existing) {
    const current = await readFile(path.join(target, 'atlas', 'modules', name), 'utf8');
    if (current.replace(/\r\n/g, '\n') !== part.replace(/\r\n/g, '\n')) {
      console.error(`DRIFT  ${name} differs from the drivers it is built from`);
      bad += 1;
    } else {
      console.log(`OK     ${name}`);
    }
  }
  process.exit(bad ? 1 : 0);
}

await writeFile(partPath, part, 'utf8');
console.log(JSON.stringify({
  wrote: partPath,
  bytes: part.length,
  sources: hashes
}, null, 2));
