/**
 * Vendor the GridAtlas Teleprinter drivers into one GridAtlas cartridge part.
 * ---------------------------------------------------------------------------
 * GridAtlas ships an immutable shell plus hashed cartridges, and a cartridge is
 * ONE classic script assembled from a list of parts. That is not a limitation
 * to be worked around; it is the thing that makes a served generation
 * reproducible. So the drivers, which are authored as ES modules here, are
 * mechanically transformed into one part rather than imported at runtime.
 *
 * WHY NOT A RUNTIME import(). The atlas is served at /gridatlas/atlas/ AND at
 * /gridatlas/atlas/v/<generation>/, and a pinned generation is byte-identical
 * to the live one. A relative specifier therefore resolves to a different place
 * depending on which URL the reader opened, and an absolute one pins a pinned
 * build to whatever the live engine happens to be tomorrow -- which is exactly
 * the "improvements went backwards into a published version" failure this
 * estate has already had once. Concatenation has neither problem.
 *
 * WHY A SCRIPT AND NOT A COPY-PASTE. A hand-copied part drifts from its source
 * silently. This records the SHA-256 of every source file in the generated
 * header, so `verify` can prove the part still matches the drivers it claims to
 * be built from, and a drifted part is a failed check rather than a surprise.
 *
 *   node drivers/gridatlas/build-part.mjs <gridatlas-repo> [--verify]
 */
import { readFile, writeFile, readdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SOURCES = ['screen-frame.js', 'print-pdf.js', 'print-source-code.js'];

const target = process.argv[2];
const verifyOnly = process.argv.includes('--verify');
if (!target) {
  console.error('usage: node build-part.mjs <gridatlas-repo> [--verify]');
  process.exit(2);
}

/* The transform is deliberately dumb and total: every `export ` prefix is
   dropped and every intra-driver import line is removed, because the three
   files become one scope. Anything cleverer -- a real module graph, a bundler
   -- would be a second thing to trust. If a driver ever imports something that
   is NOT one of its siblings, this refuses rather than emitting a part with a
   dangling reference. */
function flatten(name, text) {
  const lines = text.split(/\r?\n/);
  const out = [];
  for (const line of lines) {
    const importMatch = line.match(/^\s*import\s+.*from\s+'\.\/([^']+)';?\s*$/);
    if (importMatch) {
      if (!SOURCES.includes(importMatch[1])) {
        throw new Error(`${name} imports ${importMatch[1]}, which is not vendored`);
      }
      continue;
    }
    if (/^\s*import\s/.test(line)) {
      throw new Error(`${name} has an import this build cannot flatten: ${line.trim()}`);
    }
    out.push(line.replace(/^(\s*)export\s+(async\s+function|function|const|let|class)\s/, '$1$2 '));
  }
  return out.join('\n');
}

const hashes = {};
const bodies = [];
for (const name of SOURCES) {
  const text = await readFile(path.join(HERE, name), 'utf8');
  hashes[name] = createHash('sha256').update(text).digest('hex');
  bodies.push(`  /* ---- ${name} (sha256 ${hashes[name].slice(0, 16)}) ---- */\n`
    + flatten(name, text).split('\n').map(l => (l ? '  ' + l : l)).join('\n'));
}

const wiring = await readFile(path.join(HERE, 'gridatlas-wiring.js'), 'utf8');
hashes['gridatlas-wiring.js'] = createHash('sha256')
  .update(wiring).digest('hex');

const header = `/**
 * TELEPRINT CONTROLS -- GENERATED. DO NOT EDIT THIS FILE.
 *
 * Built by teleprinter/drivers/gridatlas/build-part.mjs from the drivers in
 * that directory, which are where any change belongs. Editing this copy makes
 * the served bytes disagree with the source they claim to come from, and
 * --verify will say so.
 *
 * Two SEPARATE functions, on the architect's instruction:
 *   Print PDF          a picture of the reader's screen, for a person
 *   Print source code  the entire source and its dependencies, for a machine
 *
 * Sources:
${Object.entries(hashes).map(([k, v]) => ` *   ${k}  sha256 ${v}`).join('\n')}
 */
`;

const part = header + '(function () {\n  \'use strict\';\n\n'
  + bodies.join('\n\n') + '\n\n'
  + wiring.split('\n').map(l => (l ? '  ' + l : l)).join('\n')
  + '\n}());\n';

const partPath = path.join(target, 'atlas', 'modules', 'teleprint-controls.js');
const existingDir = await readdir(path.join(target, 'atlas', 'modules'));
const existing = existingDir.filter(name => /teleprint-controls\.js$/.test(name));

if (verifyOnly) {
  if (!existing.length) {
    console.error('no vendored teleprint-controls part found');
    process.exit(1);
  }
  /* ONLY THE PART THAT IS SERVED.
     ------------------------------------------------------------------------
     The first version of this compared EVERY vendored part against a fresh
     build and reported DRIFT on the older ones. That is backwards: a
     generation is immutable, so a part from an earlier composition is SUPPOSED
     to differ from today's drivers, and flagging it red trains the reader to
     ignore the check. The question worth asking is narrower — does the part
     the CURRENT composition actually serves match the drivers it claims in its
     own header to be built from?

     Older parts are still listed, as history, without a verdict. */
  const current = JSON.parse(
    await readFile(path.join(target, 'atlas', 'current.json'), 'utf8'));
  const holder = current.cartridges
    .map(cartridge => cartridge.assembled_from)
    .filter(Boolean);
  let servedPart = null;
  for (const manifest of holder) {
    const text = await readFile(
      path.join(target, 'atlas', String(manifest).replace(/^\.\//, '')), 'utf8');
    const hit = text.match(/(\d{12}-teleprint-controls\.js)/);
    if (hit) { servedPart = hit[1]; break; }
  }
  if (!servedPart) {
    /* Fall back to the newest, and SAY that is what happened rather than
       silently verifying something the composition may not use. */
    servedPart = existing.sort().reverse()[0];
    console.log(`note   current.json names no parts manifest; verifying newest part ${servedPart}`);
  }
  const served = await readFile(path.join(target, 'atlas', 'modules', servedPart), 'utf8');
  const matches = served.replace(/\r\n/g, '\n') === part.replace(/\r\n/g, '\n');
  console.log(`${matches ? 'OK    ' : 'DRIFT '} ${servedPart} (served by generation ${current.generation})`);
  const history = existing.filter(name => name !== servedPart);
  if (history.length) console.log(`history ${history.length} superseded part(s), not verified: ${history.join(', ')}`);
  process.exit(matches ? 0 : 1);
}

/* PARSE THE THING THAT SHIPS, NOT THE THING IT CAME FROM.
   ------------------------------------------------------------------------
   On 2026-09-05 this build emitted a part containing a single-quoted string
   with a raw line break. `node --check` passed on the ES module it was
   flattened from -- a different file -- so nothing caught it, the part went
   into a cartridge, the cartridge went live, and window.initVentusMap never
   ran: no map, no menu bar, no layer controls, in every browser. The architect
   found it on the live site.

   A generated file that is never parsed is a generated file that is not
   checked. This refuses to write one that does not parse. */
const { writeFileSync, unlinkSync } = await import('node:fs');
const os = await import('node:os');
const probe = path.join(os.tmpdir(), `teleprint-part-${Date.now()}.js`);
writeFileSync(probe, part, 'utf8');
try {
  const checked = spawnSync(process.execPath, ['--check', probe], { encoding: 'utf8' });
  if (checked.status !== 0) {
    console.error('the generated part does not parse; refusing to write it');
    console.error(checked.stderr);
    process.exit(1);
  }
} finally {
  try { unlinkSync(probe); } catch (_) { /* nothing to clean */ }
}

await writeFile(partPath, part, 'utf8');
console.log(JSON.stringify({
  wrote: partPath,
  bytes: part.length,
  sources: hashes
}, null, 2));
